[package]
name = "wizctl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
derive-getters = "0.5.0"
regex = "1.11.1"
serde = { version = "1.0.215", features=["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.6"
